In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("C://Users//lokes//OneDrive//Desktop//Neural_Network//Amazon.csv")

In [3]:
df.head()

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Returned
0,1,D,Flight,4,2,177,3,low,F,44,1233,1
1,2,F,Flight,4,5,216,2,low,M,59,3088,1
2,3,A,Flight,2,2,183,4,low,M,48,3374,1
3,4,B,Flight,3,3,176,4,medium,M,10,1177,1
4,5,C,Flight,2,2,184,3,medium,F,46,2484,1

In [4]:
df.shape

(10999, 12)

In [5]:
df.isnull().sum()

ID                     0
Warehouse_block        0
Mode_of_Shipment       0
Customer_care_calls    0
Customer_rating        0
Cost_of_the_Product    0
Prior_purchases        0
Product_importance     0
Gender                 0
Discount_offered       0
Weight_in_gms          0
Returned               0
dtype: int64

In [6]:
df.dropna(inplace=True)

In [7]:
df.columns

Index(['ID', 'Warehouse_block', 'Mode_of_Shipment', 'Customer_care_calls',
       'Customer_rating', 'Cost_of_the_Product', 'Prior_purchases',
       'Product_importance', 'Gender', 'Discount_offered', 'Weight_in_gms',
       'Returned'],
      dtype='object')

In [8]:
df.Returned.unique()

array([1, 0])

In [9]:
df.drop('ID', axis=1, inplace=True)

In [10]:
X = df.drop('Returned', axis=1)
y = df['Returned']

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10999 entries, 0 to 10998
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Warehouse_block      10999 non-null  object
 1   Mode_of_Shipment     10999 non-null  object
 2   Customer_care_calls  10999 non-null  int64
 3   Customer_rating      10999 non-null  int64
 4   Cost_of_the_Product  10999 non-null  int64
 5   Prior_purchases      10999 non-null  int64
 6   Product_importance   10999 non-null  object
 7   Gender               10999 non-null  object
 8   Discount_offered     10999 non-null  int64
 9   Weight_in_gms        10999 non-null  int64
 10  Returned             10999 non-null  int64
dtypes: int64(7), object(4)
memory usage: 945.4+ KB

In [12]:
[np.random.rand(3,3) <0.8]

[array([[ True,  True,  True],
        [ True,  True, False],
        [ True,  True,  True]])]

In [13]:
import tensorflow
import keras

In [14]:
dir(keras.layers.Dropout)

['__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_add_trackable_child',
 '_add_variable_with_custom_getter',
 '_api_export_path',
 '_api_export_symbol_id',
 '_assert_input_compatibility',
 '_build_at_init',
 '_build_by_run_for_kwargs',
 '_build_by_run_for_single_pos_arg',
 '_check_load_own_variables',
 '_check_quantize_args',
 '_check_super_called',
 '_checkpoint_adapter',
 '_checkpoint_dependencies',
 '_clear_losses',
 '_copy_trackable_to_cpu',
 '_default_save_signature',
 '_deferred_dependencies',
 '_delete_tracking',
 '_deserialization_dependencies',
 '_deserialize_from_proto',
 '_export_to_saved_model_graph',
 '_flatten_layers',
 '_float8_call',
 '_gather_saveables_for_checkpoint',
 '_get_call_context',
 '_get_node_attribute_at_index',
 '_get_own_losses',
 '_get_regularization_losses',
 '_gptq_call',
 '_handle_deferred_dependencies',
 '_initialize_tracker',
 '_int4_call',
 '_int8_call',
 '_lock_state',
 '_lookup_dependency',
 '_maybe_build',
 '_maybe_initialize_trackable',
 '_maybe_reset_call_context',
 '_name_based_attribute_restore',
 '_name_based_restores',
 '_no_dependency',
 '_not_implemented_error',
 '_obj_type',
 '_object_identifier',
 '_open_name_scope',
 '_post_build',
 '_post_track_variable',
 '_post_untrack_variable',
 '_preload_simple_restoration',
 '_quantization_mode_error',
 '_register_call_context_args',
 '_resolve_and_populate_arg',
 '_restore_from_tensors',
 '_serialize_to_proto',
 '_serialize_to_tensors',
 '_set_mask_metadata',
 '_set_save_spec',
 '_setattr_hook',
 '_setattr_tracking',
 '_tf_api_names',
 '_tf_api_names_v1',
 '_track_trackable',
 '_track_variable',
 '_trackable_children',
 '_unconditional_checkpoint_dependencies',
 '_unconditional_dependency_names',
 '_unpickle_model',
 '_untrack_variable',
 '_update_uid',
 'add_loss',
 'add_metric',
 'add_variable',
 'add_weight',
 'build',
 'build_from_config',
 'call',
 'compute_dtype',
 'compute_mask',
 'compute_output_shape',
 'compute_output_spec',
 'count_params',
 'dtype',
 'dtype_policy',
 'from_config',
 'get_build_config',
 'get_config',
 'get_weights',
 'input',
 'input_dtype',
 'input_spec',
 'load_own_variables',
 'losses',
 'metrics',
 'metrics_variables',
 'non_trainable_variables',
 'non_trainable_weights',
 'output',
 'path',
 'quantization_mode',
 'quantize',
 'quantized_build',
 'quantized_call',
 'rematerialized_call',
 'save_own_variables',
 'set_weights',
 'stateless_call',
 'supports_masking',
 'symbolic_call',
 'trainable',
 'trainable_variables',
 'trainable_weights',
 'variable_dtype',
 'variables',
 'weights']

In [15]:
np.exp(-10).round(4)

np.float64(0.0)

In [16]:
num_cols = df.select_dtypes(include=np.number).columns.tolist()

In [17]:
cat_cols = list(set(df.columns).difference(num_cols))

In [18]:
cat_cols

['Mode_of_Shipment', 'Warehouse_block', 'Gender', 'Product_importance']

In [19]:
df[cat_cols].head()

  Mode_of_Shipment Warehouse_block Gender Product_importance
0           Flight               D      F                low
1           Flight               F      M                low
2           Flight               A      M                low
3           Flight               B      M             medium
4           Flight               C      F             medium

In [20]:
df['Warehouse_block'].unique()

array(['D', 'F', 'A', 'B', 'C'], dtype=object)

In [21]:
df['Gender'].unique()

array(['F', 'M'], dtype=object)

In [22]:
df['Product_importance'].unique()

array(['low', 'medium', 'high'], dtype=object)

In [23]:
df['Mode_of_Shipment'].unique()

array(['Flight', 'Ship', 'Road'], dtype=object)

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X, X_test, Y, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [26]:
X_train, X_val,y_train,y_val = train_test_split(X,Y,test_size=0.1, random_state=42)

In [27]:
# Performing One-Hot Encoding increases featurres by 13 more columns, which increases building complexity in modelling

In [28]:
from category_encoders import TargetEncoder

In [29]:
T_encoder = TargetEncoder(cat_cols)

In [30]:
X_train = T_encoder.fit_transform(X_train, y_train)
X_val = T_encoder.fit_transform(X_val, y_val)
X_test = T_encoder.fit_transform(X_test, y_test)

In [31]:
X_train.head()

,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms
9567,0.602317,0.580829,5,4,201,2,0.596770,0.595514,5,5593
2981,0.601215,0.598370,3,1,250,3,0.596770,0.597570,8,3617
5092,0.603151,0.598370,3,5,217,2,0.587562,0.597570,6,5182
8761,0.601215,0.580829,3,4,136,3,0.587562,0.595514,6,4631
7045,0.601215,0.598370,4,4,153,5,0.587562,0.595514,9,5818

In [34]:
X_train[cat_cols].head()

      Mode_of_Shipment  Warehouse_block    Gender  Product_importance
9567          0.580829         0.602317  0.595514            0.596770
2981          0.598370         0.601215  0.597570            0.596770
5092          0.598370         0.603151  0.597570            0.587562
8761          0.580829         0.601215  0.595514            0.587562
7045          0.598370         0.601215  0.595514            0.587562

In [35]:
X_train['Mode_of_Shipment'].unique()

array([0.58082859, 0.59836977, 0.60387597])

In [36]:
df['Mode_of_Shipment'].unique()

array(['Flight', 'Ship', 'Road'], dtype=object)

In [37]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [38]:
sc = StandardScaler()

In [41]:
X_train = sc.fit_transform(X_train)
X_val = sc.fit_transform(X_val)
X_test = sc.fit_transform(X_test)

In [42]:
import tensorflow as tf
import keras

In [43]:
from keras import Sequential
from keras.layers import Dense

In [45]:
from keras.layers import Dropout

In [44]:
np.random.seed(42)
tf.random.set_seed(42)

In [54]:
def create_baseline():
    L2_reg = keras.regularizers.L2(l2=1e-2)

    model = Sequential(
        [
            Dense(256, activation='relu', kernel_regularizer=L2_reg),
            Dropout(0.3),
            Dense(128, activation='relu', kernel_regularizer=L2_reg),
            Dropout(0.2),
            Dense(64, activation='relu', kernel_regularizer=L2_reg),
            Dense(1, activation='sigmoid')
        ]
    )

    return model

In [55]:
model = create_baseline()

In [57]:
model.compile(
    optimizer=tf.keras.optimizers.Adam(),
    loss = tf.keras.losses.BinaryCrossentropy,
    metrics = ['accuracy']
)

In [61]:
history = model.fit(X_train, y_train, epochs=15, batch_size=128, verbose=1)

Epoch 1/15
62/62 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.6358 - loss: 2.2038
Epoch 2/15
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6495 - loss: 1.0007
Epoch 3/15
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6565 - loss: 0.6776
Epoch 4/15
62/62 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6553 - loss: 0.5974
Epoch 5/15
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6607 - loss: 0.5745
Epoch 6/15
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6578 - loss: 0.5668
Epoch 7/15
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6662 - loss: 0.5633
Epoch 8/15
62/62 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6642 - loss: 0.5623
Epoch 9/15
62/62 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6659 - loss: 0.5607
Epoch 10/15
62/62 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6661 - loss: 0.5594
Epoch 11/15
62/62 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6645 - loss: 0.5585
Epoch 12/15
62/62 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6681 - loss: 0.5572
Epoch 13/15
62/62 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6642 - loss: 0.5561
Epoch 14/15
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6631 - loss: 0.5565
Epoch 15/15
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6669 - loss: 0.5547

In [62]:
model.evaluate(X_train, y_train)

248/248 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6700 - loss: 0.5509

[0.5509240627288818, 0.6700341105461121]

In [63]:
model.evaluate(X_val, y_val)

28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6625 - loss: 0.5524

[0.5524119138717651, 0.6625000238418579]

In [64]:
from keras.layers import Dense
from keras.layers import Activation 
from keras.layers import BatchNormalization

In [74]:
def create_baselin_batch_norm():
    L2_reg = keras.regularizers.L2(l2=1e-2)
    model_1 = Sequential(
        [
            Dense(256, kernel_regularizer=L2_reg),
            BatchNormalization(),
            Activation('relu'),
            Dropout(0.3),

            Dense(128, kernel_regularizer=L2_reg),
            BatchNormalization(),
            Activation('relu'),
            Dropout(0.2),

            Dense(64,kernel_regularizer=L2_reg ),
            BatchNormalization(),
            Activation('relu'),

            Dense(1, activation='sigmoid')
        ]
    )

    return model_1

In [75]:
model_1 = create_baselin_batch_norm()

In [77]:
model.compile(
    optimizer = keras.optimizers.Adam(),
    loss = keras.losses.BinaryCrossentropy,
    metrics = ['accuracy']
)